spring:
  security:
    oauth2:
      client:
        provider:
          external:
            issuer-uri: http://0.0.0.0:8080/realms/spring-boot-realm
        registration:
          external:
            provider: external
            client-name: spring-boot-client
            client-id: spring-boot-client
            client-secret: HE0xFRNnpW9NTG6QBWj62ZnCgsmlmD2v
            scope: openid, offline_access, profile
            authorization-grant-type: authorization_code
server:
  port: 8081

security:
  success-url: http://localhost:8081/
  logout-url: http://0.0.0.0:8080/realms/spring-boot-realm/protocol/openid-connect/logout
  redirect-uri: http://localhost:8081/